plugins { 
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish' 
}

version = project.mod_version
group = project.maven_group
base { archivesName = project.archives_base_name }

repositories { 
    mavenCentral() 
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

loom { 
    splitEnvironmentSourceSets()
    mods { 
        flatmine { 
            sourceSet sourceSets.main
            sourceSet sourceSets.client 
        } 
    } 
}

// Thêm cấu hình liên kết classpath cho thư mục test nhận diện thư viện Minecraft
sourceSets {
    test {
        compileClasspath += sourceSets.main.compileClasspath + sourceSets.main.output
        runtimeClasspath += sourceSets.main.runtimeClasspath + sourceSets.main.output
    }
}

processResources { 
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { 
        expand 'version': project.version 
    } 
}

tasks.withType(JavaCompile).configureEach { 
    it.options.release = 21 
}

java { 
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21 
}

test { 
    useJUnitPlatform() 
}

jar { 
    from('LICENSE') { 
        rename { "${it}_${project.base.archivesName.get()}" } 
    } 
}